// Generated by wrangler types (manual for initial scaffold)
interface Env {
  GRIMOIRE_DB: D1Database
  HOBBOT_DB: D1Database
  AI: Ai
  ANTHROPIC_API_KEY: string
  DASHSCOPE_API_KEY: string
  PROVIDER_HEALTH: KVNamespace
  AI_GATEWAY_ACCOUNT_ID: string
  AI_GATEWAY_NAME: string
  AI_GATEWAY_TOKEN: string
  MESSAGE_RATE_LIMIT: RateLimit
  SESSION_RATE_LIMIT: RateLimit
  ENVIRONMENT: 'development' | 'production'
}
